spec-version: 0.36.0

name: hspec-hedgehog
version: 0.2.0.0
synopsis: Integrate Hedgehog and Hspec!
description: Please see the README on GitHub at <https://github.com/hspec/hspec-hedgehog#readme>
category: Testing
author: Matt Parsons
maintainer: parsonsmatt@gmail.com
copyright: 2020 Matt Parsons

extra-source-files:
  - README.md
  - ChangeLog.md

github: hspec/hspec-hedgehog

dependencies:
  - base >= 4.7 && < 5
  - hspec >= 2.11.0 && < 3
  - hspec-core >= 2.11.0 && < 3
  - hedgehog >= 1.5

library:
  source-dirs: src
  dependencies:
    - QuickCheck >= 2.9.2 && < 3
    - splitmix >= 0.0.1 && < 1

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools: hspec-discover
    dependencies:
      - HUnit
      - QuickCheck
      - hspec-hedgehog
